apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_REGION}

vpc:
  id: ${VPC_ID}
  subnets:
    public:
      ${AWS_REGION_1}: { id: ${PUBLIC_SUBNET_1_ID} }
      ${AWS_REGION_2}: { id: ${PUBLIC_SUBNET_2_ID} }
    private:
      ${AWS_REGION_1}: { id: ${PRIVATE_SUBNET_1_ID} }
      ${AWS_REGION_2}: { id: ${PRIVATE_SUBNET_2_ID} }

managedNodeGroups:
  - name: eks-nodegroup
    minSize: 4
    maxSize: 5
    desiredCapacity: 4
    instanceType: ${INSTANCE_TYPE}
    labels: { role: worker }
    privateNetworking: true