cluster_name: "mm-eks-cluster"
region: "us-east-2"
azs_a: "us-east-2a"
azs_b: "us-east-2b"
instance_type: "t2.small"

secret_contents: "{{ lookup('aws_secret', 'network-config') }}"
clusterconfig: 
  VPC_ID: "{{ secret_contents.vpc_id }}"
  CLUSTER_NAME: "{{ cluster_name }}"
  AWS_REGION: "{{ region }}"
  AWS_REGION_1: "{{ azs_a }}"
  AWS_REGION_2: "{{ azs_b }}"
  PUBLIC_SUBNET_1_ID: "{{ secret_contents.public_id_1 }}"
  PUBLIC_SUBNET_2_ID: "{{ secret_contents.public_id_2 }}"
  PRIVATE_SUBNET_1_ID: "{{ secret_contents.private_id_1 }}"
  PRIVATE_SUBNET_2_ID: "{{ secret_contents.private_id_2}}"
  INSTANCE_TYPE: "{{ instance_type }}"
  PEM_PATH: "~/.ssh/id_rsa.pub"
  
secret_contents_data: "{{ lookup('aws_secret', 'microservice-secrets', region='us-east-1') }}"
data:
  DB_ENDPOINT: "{{ secret_contents_data.DB_ENDPOINT }}"
  DB_HOST: "aline-db-service"
  DB_PORT: "3306"
  DB_NAME: "alinedb-mm"
  DB_USERNAME: "{{ secret_contents_data.DB_USERNAME }}"
  DB_PASSWORD: "{{ secret_contents_data.DB_PASSWORD }}"
  ENCRYPT_SECRET_KEY: "{{ secret_contents_data.ENCRYPT_SECRET_KEY }}"
  JWT_SECRET_KEY: "{{ secret_contents_data.JWT_SECRET_KEY }}"

services:
  AWS_ID: "862167864120"
  AWS_ECR_REGION: "us-east-1"